# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'app/static/ui/verification.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(795, 492)
        Form.setStyleSheet("QWidget{\n"
"    border:1px solid red;\n"
"}")
        self.horizontalLayout = QtWidgets.QHBoxLayout(Form)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame = QtWidgets.QFrame(Form)
        self.frame.setStyleSheet("")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame_title = QtWidgets.QFrame(self.frame)
        self.frame_title.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_title.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_title.setObjectName("frame_title")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.frame_title)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_9 = QtWidgets.QLabel(self.frame_title)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_8.addWidget(self.label_9, 0, QtCore.Qt.AlignLeft)
        self.verticalLayout.addWidget(self.frame_title)
        self.frame_backgorund = QtWidgets.QFrame(self.frame)
        self.frame_backgorund.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_backgorund.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_backgorund.setObjectName("frame_backgorund")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame_backgorund)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.frame_blank = QtWidgets.QFrame(self.frame_backgorund)
        self.frame_blank.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_blank.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_blank.setObjectName("frame_blank")
        self.horizontalLayout_3.addWidget(self.frame_blank, 0, QtCore.Qt.AlignBottom)
        self.frame_login_and_signup = QtWidgets.QFrame(self.frame_backgorund)
        self.frame_login_and_signup.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_login_and_signup.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_login_and_signup.setObjectName("frame_login_and_signup")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame_login_and_signup)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_3.addWidget(self.frame_login_and_signup)
        self.horizontalLayout_3.setStretch(0, 2)
        self.horizontalLayout_3.setStretch(1, 1)
        self.verticalLayout.addWidget(self.frame_backgorund)
        self.frame_other = QtWidgets.QFrame(self.frame)
        self.frame_other.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_other.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_other.setObjectName("frame_other")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_other)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem = QtWidgets.QSpacerItem(186, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.label = QtWidgets.QLabel(self.frame_other)
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        self.label_2 = QtWidgets.QLabel(self.frame_other)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.label_3 = QtWidgets.QLabel(self.frame_other)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_2.addWidget(self.label_3)
        self.label_4 = QtWidgets.QLabel(self.frame_other)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_2.addWidget(self.label_4)
        self.label_5 = QtWidgets.QLabel(self.frame_other)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_2.addWidget(self.label_5)
        self.label_6 = QtWidgets.QLabel(self.frame_other)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_2.addWidget(self.label_6)
        spacerItem1 = QtWidgets.QSpacerItem(185, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.verticalLayout.addWidget(self.frame_other)
        self.verticalLayout.setStretch(0, 1)
        self.verticalLayout.setStretch(1, 5)
        self.verticalLayout.setStretch(2, 1)
        self.horizontalLayout.addWidget(self.frame)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_9.setText(_translate("Form", "项目名称"))
        self.label.setText(_translate("Form", "关于我们"))
        self.label_2.setText(_translate("Form", "加入我们"))
        self.label_3.setText(_translate("Form", "人才招聘"))
        self.label_4.setText(_translate("Form", "广告服务"))
        self.label_5.setText(_translate("Form", "友情链接"))
        self.label_6.setText(_translate("Form", "商场社区"))
